/**
 * Builds src/constants/currencies.ts (symbol and decimals of every currency the app offers) and
 * src/i18n/currencyNames.ts (their names in the nine app languages).
 * The list is what the exchange rate source returns (see src/services/exchangeRates.ts), minus the
 * codes Node's Intl has no name for and the ones that are not money people are paid in.
 * Run after the source adds or drops a currency: `npm run currencies`.
 */
import fs from 'node:fs';
import path from 'node:path';

import { LANGUAGES } from '../src/i18n';

const SOURCE_URL = 'https://open.er-api.com/v6/latest/USD';
const root = path.join(__dirname, '..');

// Metals, the IMF unit and Chile's unit of account. Of the X codes only the shared currencies stay.
const SHARED_X_CODES = ['XAF', 'XCD', 'XCG', 'XOF', 'XPF'];
const EXCLUDED = ['CLF'];

// Shown like this since the first version: kept so nothing changes on screen for existing profiles.
const FIXED_SYMBOLS: Record<string, string> = {
  EUR: '€',
  USD: '$',
  GBP: '£',
  JPY: '¥',
  CAD: 'CA$',
  AUD: 'A$',
  CHF: 'CHF ',
};

const part = (code: string, display: 'symbol' | 'narrowSymbol'): string =>
  new Intl.NumberFormat('en', { style: 'currency', currency: code, currencyDisplay: display })
    .formatToParts(1)
    .find((item) => item.type === 'currency')?.value ?? code;

/** The symbol goes straight in front of the number, so one that ends in a letter gets a space. */
function symbolFor(code: string): string {
  if (FIXED_SYMBOLS[code]) return FIXED_SYMBOLS[code];
  const wide = part(code, 'symbol');
  const narrow = part(code, 'narrowSymbol');
  const symbol = wide !== code ? wide : narrow !== code ? narrow : code;
  return /[\p{L}.]$/u.test(symbol) ? `${symbol} ` : symbol;
}

const decimalsFor = (code: string): number =>
  new Intl.NumberFormat('en', { style: 'currency', currency: code }).resolvedOptions().maximumFractionDigits ?? 2;

function nameFor(code: string, language: string): string | null {
  const name = new Intl.DisplayNames(language, { type: 'currency', fallback: 'none' }).of(code);
  if (!name) return null;
  return name.charAt(0).toLocaleUpperCase(language) + name.slice(1);
}

const quote = (text: string): string => `'${text.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;

async function main() {
  const response = await fetch(SOURCE_URL);
  const body = (await response.json()) as { result?: string; rates?: Record<string, number> };
  if (body.result !== 'success' || !body.rates) throw new Error(`No rates from ${SOURCE_URL}`);

  const languages = LANGUAGES.map((language) => language.code);
  const skipped: string[] = [];
  const codes = Object.keys(body.rates)
    .filter((code) => /^[A-Z]{3}$/.test(code))
    .filter((code) => {
      const offered =
        !EXCLUDED.includes(code) &&
        (!code.startsWith('X') || SHARED_X_CODES.includes(code)) &&
        languages.every((language) => nameFor(code, language) !== null);
      if (!offered) skipped.push(code);
      return offered;
    })
    .sort();

  const header = '// Generated by scripts/build-currencies.ts (`npm run currencies`). Do not edit by hand.\n';

  const currencyLines = codes.map(
    (code) => `  ${code}: { symbol: ${quote(symbolFor(code))}, decimals: ${decimalsFor(code)} },`
  );
  fs.writeFileSync(
    path.join(root, 'src', 'constants', 'currencies.ts'),
    `${header}
export interface CurrencyInfo {
  /** Goes straight in front of the number; a symbol made of letters ends in a space. */
  symbol: string;
  /** Digits after the decimal separator: 0 (yen), 2 or 3 (Kuwaiti dinar). */
  decimals: number;
}

export const DEFAULT_CURRENCY = 'EUR';

export const CURRENCIES: Record<string, CurrencyInfo> = {
${currencyLines.join('\n')}
};

/** Every currency the app offers, sorted by code. */
export const CURRENCY_CODES: readonly string[] = Object.keys(CURRENCIES);

/** A code the app does not know (an older backup, a currency that was dropped) is shown by its code. */
export const currencyInfo = (code: string | null | undefined): CurrencyInfo => {
  if (!code) return CURRENCIES[DEFAULT_CURRENCY];
  return Object.prototype.hasOwnProperty.call(CURRENCIES, code) ? CURRENCIES[code] : { symbol: \`\${code} \`, decimals: 2 };
};
`
  );

  const nameBlocks = languages.map((language) => {
    const lines = codes.map((code) => `    ${code}: ${quote(nameFor(code, language) ?? code)},`);
    return `  ${language}: {\n${lines.join('\n')}\n  },`;
  });
  fs.writeFileSync(
    path.join(root, 'src', 'i18n', 'currencyNames.ts'),
    `${header}import type { LanguageCode } from './index';

export const CURRENCY_NAMES: Record<LanguageCode, Record<string, string>> = {
${nameBlocks.join('\n')}
};

/** Name of a currency in the given language; the code itself when the app does not know it. */
export const currencyLabel = (code: string, language: LanguageCode): string => {
  if (!Object.prototype.hasOwnProperty.call(CURRENCY_NAMES.en, code)) return code;
  return CURRENCY_NAMES[language]?.[code] ?? CURRENCY_NAMES.en[code];
};
`
  );

  console.log(`${codes.length} currencies written. Left out: ${skipped.join(', ') || 'none'}.`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
